name: wave_voice
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - poppler
  - poppler-data
  - click
  ### PIP -----------------------------------------------------------------------
  - pip
  - pip:
    - google-cloud-texttospeech>=2
  ### DEVELOPMENT ---------------------------------------------------------------
  - pep8
  - pylint
  - pycodestyle
  - autopep8
  - chardet
  - ipython
